#
# kubectl -n apache-airflow apply -f setup/local/airflow/airflow-secrets.yaml
#
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  # The sql_alchemy_conn value is a base64 encoded representation of this connection string:
  # postgresql+psycopg2://pgadmin:pgadmin@postgres:5432/airflow
  # cG9zdGdyZXNxbCtwc3ljb3BnMjovL3BnYWRtaW46cGdhZG1pbkBwb3N0Z3Jlczo1NDMyL2FpcmZsb3c=
  #
  # postgresql+psycopg2://pgadmin:pgadmin@postgres.postgres.svc.cluster.local:5432/airflow
  # cG9zdGdyZXNxbCtwc3ljb3BnMjovL3BnYWRtaW46cGdhZG1pbkBwb3N0Z3Jlcy5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2FpcmZsb3c=
  #
  sql_alchemy_conn: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3BnYWRtaW46cGdhZG1pbkBwb3N0Z3Jlcy5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2FpcmZsb3c=