#
# kubectl -n apache-airflow apply -f setup/local/airflow/airflow-service.yml
#
# kubectl -n apache-airflow delete -f setup/local/airflow/airflow-service.yml
#
---

apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
spec:
  type: NodePort
  ports:
    - name: airflow-webserver
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31500
  selector:
    app: airflow-webserver

---
