#
# kubectl -n grafana apply -f setup/local/grafana/grafana-configmap.yaml
#
# kubectl -n grafana delete -f setup/local/grafana/grafana-configmap.yaml
#
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: grafana
data:
  prometheus.yaml: |-
    { 
        "apiVersion": 1, 
        "datasources": [ 
            { 
               "access":"proxy", 
                "editable": true, 
                "name": "prometheus", 
                "orgId": 1, 
                "type": "prometheus", 
                "url": "http://prometheus-service.prometheus.svc:9090", 
                "version": 1 
            } 
        ] 
    }