#
# kubectl -n prometheus apply -f setup/local/prometheus/prometheus-volumes.yaml
#
# kubectl -n prometheus delete -f setup/local/prometheus/prometheus-volumes.yaml
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    type: nfs
    app: prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/nfs_share/prometheus
    server: 192.168.122.1
    readOnly: false
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  labels:
    type: nfs
    app: prometheus
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi