#
# kubectl -n k8s-spark apply -f setup/volumes/nfs-storage/nfs-storage-pv.yaml
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # It will not be automatically deleted when a user deletes claim
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  local:
    path: /mnt/nfs-share
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - thinkpad