#
# kubectl apply -f setup/admin/user-csr.yaml
#
---

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: brijeshdhaker-csr
spec:
  groups:
    - system:masters
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2d6Q0NBV3NDQVFBd1BqRVdNQlFHQTFVRUF3d05ZbkpwYW1WemFHUm9ZV3RsY2pFVU1CSUdBMVVFQ2d3TApaVzVuYVc1bFpYSnBibWN4RGpBTUJnTlZCQW9NQldGa2JXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUExazVSZDRWWHRWUittdkc2MGczQUxSc2EvcnBQVE9Pazk0Z0d3Um9kdU5jcStmbjEKUEN4RDVTa3FIaHlhbWhTeUowL1pQaDB4REtBeld1dVVwQk9Wa2R3N0d2Mk1iVTYybTZVajl4VkZZeUt3YXVIQwpBcTQ3eTY5ZllkeUNwemZZbWhUSHhwYlo3cDBJUjM1Q2I4NDcydmJ6RGhQQ09rRjM0bERkOUhDdU1sWnV5UXF1CmhudXpXbWFodkxXM2xEb0pSNnRMbUpnZHVrT3h3K0VZTWtETHptT01JZEpIeFh2eWFpYmhDQXRvNm1JVmlJdjcKU3lIOXp1MUJFLzBZcms4a0ZoeDZoM043aVdLMzVZY3dFTHNMRG16NkF4RGF0TmFpcVBYV0lLd0RqTG4vMGphYgorVVVxUXF1d1ZzdDMwcEhtRHRhNjV6MkxNbkVGWlhQQVQ3cS9Xd0lEQVFBQm9BQXdEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0VCQUcwVm1KcU9XQU1lTTRSMjVPMy9tcXhwTXVaMVNIdnpxc0U1SnZOT0I0aldwME9WcXBhTmN1Z20Kc3VqdXh5UCtsUkoybEdwZTVoU09yOExoQ09UTlFnR2lhbEFaMTNJcFY0OXQyRjRYZ0RiQW5wYnhpMUl3REU0VwpRbWVlTXBxMlNoaTlFaW9wQzM3RTdrek1Md0d2eGpKQjBSdSt2Z0kreWRQdUwrWFd3QTFSUjZiUHBsNHJxdmNiCkx1UG9VaHBPMDBYSjV1Y0dDazBraHVndjZ2QzZQeTNCclIwblg2SWU2NU1NSUY1UEtLN1dvdkw5b3k2elg2RVcKN0V1VE9ROStCOHhKYWo4R014Snc2dmNvd2pXNk0xUFpZMW0vODNwUW51dlRJRnRudEcwbEVwWjc4RUVtVk1idwpOTVZoaittVzRCNGRkZVpkNXV4NTlVTmRQdjFpdVlRPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  expirationSeconds: 864000
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - "digital signature"
    - "key encipherment"
    - "client auth"
