#
# kubectl -n apache-airflow apply -f setup/airflow/airflow-service.yaml
#
# kubectl -n apache-airflow delete -f setup/airflow/airflow-service.yaml
#
# kubectl -n apache-airflow port-forward svc/airflow-webserver 4040:4040
---

apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
spec:
  type: NodePort
  ports:
    - name: airflow-webserver
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31500
  selector:
    app: airflow-webserver

---
