#
# kubectl -n metallb-system  apply -f setup/local/metallb-system/address-pool.yaml
#
# kubectl -n metallb-system  delete -f setup/local/metallb-system/address-pool.yaml
#
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-addresspool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.122.100-192.168.122.252

#
---
#

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-addresspool

---