#
# kubectl -n default apply -f setup/local/account/service-account-role.yml
# kubectl -n default create clusterrolebinding spark-role --clusterrole=cluster-admin --serviceaccount=default:spark --dry-run=client -o yaml
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: spark-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: default
