#
# kubectl -n default apply -f setup/local/account/service-account.yml
# kubectl -n default create serviceaccount spark
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: default