apiVersion: v1
data:
  influxdb.conf: |
    reporting-disabled = false
    bind-address = ":8088"

    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"

    [coordinator]

    [retention]

    [shard-precreation]

    [monitor]

    [subscriber]

    [http]

    # TODO: allow multiple graphite listeners
    [[graphite]]
      enabled = true
      bind-address = ":2003"
      database = "graphite"
      retention-policy = ""
      protocol = "tcp"
      batch-size = 5000
      batch-pending = 10
      batch-timeout = "1s"
      consistency-level = "one"
      separator = "."
      udp-read-buffer = 0
      templates = [
      # JVM source
      "*.*.jvm.pools.* username.applicationid.process.namespace.namespace.measurement*",
      # YARN source
      "*.*.applicationMaster.* username.applicationid.namespace.measurement*",
      # shuffle service source
      "*.shuffleService.* username.namespace.measurement*",
      # streaming
      "*.*.*.spark.streaming.* username.applicationid.process.namespace.namespace.id.measurement*",
      # generic template for driver and executor sources
      "username.applicationid.process.namespace.measurement*" ]

    # TODO: allow multiple collectd listeners with templates
    [[collectd]]

    # TODO: allow multiple opentsdb listeners with templates

    [[opentsdb]]

    # TODO: allow multiple udp listeners with templates

    [[udp]]

    [continuous_queries]

    [logging]
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: influxdb
    meta.helm.sh/release-namespace: influxdb
  creationTimestamp: "2023-02-04T18:14:23Z"
  labels:
    app.kubernetes.io/instance: influxdb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/version: 1.8.10
    helm.sh/chart: influxdb-4.12.0
  name: influxdb
  namespace: influxdb