#
#
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: influxdb
    meta.helm.sh/release-namespace: influxdb
  labels:
    app.kubernetes.io/instance: influxdb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/version: 1.8.10
    helm.sh/chart: influxdb-4.12.0
  name: influxdb
  namespace: influxdb
spec:
  clusterIP: 10.106.39.17
  clusterIPs:
  - 10.106.39.17
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api
    port: 8086
    protocol: TCP
    targetPort: api
  - name: rpc
    port: 8088
    protocol: TCP
    targetPort: rpc
  - name: graphite
    port: 2003
    protocol: TCP
    targetPort: 2003
  selector:
    app.kubernetes.io/instance: influxdb
    app.kubernetes.io/name: influxdb
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
