#
# kubectl -n spark-apps apply -f setup/local/spark-apps/jobs/spark-jmx.yaml
#
# kubectl -n spark-apps delete -f setup/local/spark-apps/jobs/spark-jmx.yaml
#
# kubectl -n spark-apps get sparkapplications spark-jmx -o=yaml
#
# kubectl -n spark-apps delete sparkapplications spark-jmx
#
# kubectl -n spark-apps describe sparkapplication spark-jmx
#

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-jmx
  namespace: spark-apps
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar"
  arguments:
    - "100000"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      app.kubernetes.io/version: 3.0.0
      app.kubernetes.io/component: spark-driver
      app.kubernetes.io/part-of: spark
      app.kubernetes.io/managed-by: self
      app.kubernetes.io/metrics-by: jmx
    serviceAccount: spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      app.kubernetes.io/version: 3.0.0
      app.kubernetes.io/component: spark-executor
      app.kubernetes.io/part-of: spark
      app.kubernetes.io/managed-by: self
      app.kubernetes.io/metrics-by: jmx
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.11.0.jar"
      port: 8090
