#
# kubectl -n k8s-spark apply -f setup/local/cassandra-service.yaml
# kubectl -n k8s-spark apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml

kind: Service
apiVersion: v1
metadata:
  name: cassandra
  namespace: k8s-spark
spec:
  clusterIP: None

---
kind: Endpoints
apiVersion: v1
metadata:
  name: cassandra
  namespace: k8s-spark
subsets:
  - addresses:
      - ip: 192.168.1.7
    ports:
      - port: 9042
