#
# kubectl -n sys-admin apply -f admin/node/serviceaccount.yaml
# kubectl -n sys-admin create serviceaccount node-admin
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-admin
  namespace: sys-admin