#
# kubectl -n spark-apps apply -f setup/local/spark-apps/service-account.yml
#
# kubectl -n spark-apps create serviceaccount spark
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark-apps