# kubectl -n k8s-spark create cm spark-apps-configmap  \
# --from-file=spark-defaults.conf=setup/local/history-server/spark-defaults.conf \
# --from-file=spark.logserver.conf=setup/local/history-server/spark.logserver.conf \
# --from-literal=workload=HistoryServer \
# --dry-run=client -o yaml

#
# kubectl -n spark-apps apply -f setup/local/spark-apps/spark-app-configmap.yaml
#
# kubectl -n spark-apps delete -f setup/local/spark-apps/spark-app-configmap.yaml
#
---
apiVersion: v1
data:
  spark-defaults.conf: |-
    # Example:
    spark.serializer                          org.apache.spark.serializer.KryoSerializer

    #
  spark.logserver.conf: |-
    #
    # History Server Related Properties
    #
    spark.history.provider                    org.apache.spark.deploy.history.FsHistoryProvider
    spark.history.fs.logDirectory             file:///mnt/nfs_share/spark-logs/
    spark.history.fs.update.interval          10s
    spark.history.ui.port                     18080
    spark.yarn.historyServer.allowTracking    true
    
    #
    #
  graphite.metrics.properties: |-
    # Example configuration for Graphite sink
    *.sink.graphite.class=org.apache.spark.metrics.sink.GraphiteSink
    *.sink.graphite.host=influxdb.influxdb.svc.cluster.local
    *.sink.graphite.port=2003
    *.sink.graphite.period=10
    *.sink.graphite.unit=seconds
    *.sink.graphite.prefix=graphite
    
    # Enable JvmSource for instance master, worker, driver and executor
    master.source.jvm.class=org.apache.spark.metrics.source.JvmSource
    worker.source.jvm.class=org.apache.spark.metrics.source.JvmSource
    driver.source.jvm.class=org.apache.spark.metrics.source.JvmSource
    executor.source.jvm.class=org.apache.spark.metrics.source.JvmSource
    
    #
    #
  prometheus.metrics.properties: |-
    #
    # Example configuration for PrometheusServlet
    #
    *.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
    *.sink.prometheusServlet.path=/metrics/prometheus
    *.sink.prometheusServlet.prefix=spark_prometheus
    master.sink.prometheusServlet.path=/metrics/master/prometheus
    applications.sink.prometheusServlet.path=/metrics/applications/prometheus
    
    #
    #
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-26T20:43:44Z"
  name: spark-apps-configmap
  namespace: spark-apps
