#
# kubectl -n spark-apps apply -f setup/local/spark-apps/spark-apps-volumes.yaml
#
# kubectl -n spark-apps delete -f setup/local/spark-apps/spark-apps-volumes.yaml
#
---
#
# kubectl -n spark-apps port-forward svc/spark-apps-jmx-service 8090:8090
#
apiVersion: v1
kind: Service
metadata:
  name: spark-apps-jmx-service
  labels:
    app.kubernetes.io/name: spark-apps-jmx-service
    app.kubernetes.io/component: spark-apps
spec:
  ports:
    - name: spark-apps-jmx-service
      port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app.kubernetes.io/metrics-by: jmx
#
---
#
# kubectl -n spark-apps port-forward svc/spark-apps-prometheus-service 4040:4040
#
apiVersion: v1
kind: Service
metadata:
  name: spark-apps-prometheus-service
  labels:
    app.kubernetes.io/name: spark-apps-prometheus-service
    app.kubernetes.io/component: spark-apps
spec:
  ports:
    - name: spark-apps-prometheus-service
      port: 4040
      targetPort: 4040
      protocol: TCP
  selector:
    app.kubernetes.io/metrics-by: prometheus

#
---
#
