#
# kubectl -n spark-operator apply -f spark-operator-monitor.yaml
#

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-operator-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sparkoperator
  endpoints:
    - port: metrics

---
apiVersion: v1
kind: Service
metadata:
  name: spark-operator-service
  labels:
    app.kubernetes.io/name: sparkoperator
spec:
  ports:
    - name: metrics
      port: 10254
      targetPort: 10254
      protocol: TCP
  selector:
    app.kubernetes.io/name: sparkoperator