#
# kubectl -n spark-apps apply -f setup/local/spark-apps/quota/object-counts.yaml
# kubectl -n spark-apps get quota object-counts
# kubectl -n spark-apps describe quota object-counts
#
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    pods: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"