#
# kubectl -n spark-apps apply -f setup/spark-apps/spark-apps-services.yaml
#
# kubectl -n spark-apps delete -f setup/spark-apps/spark-apps-services.yaml
#
---
#
#
#
apiVersion: v1
kind: Service
metadata:
  name: spark-historyserver
spec:
  ports:
    - nodePort: 31808
      port: 18080
      protocol: TCP
      targetPort: 18080
  selector:
    name: spark-historyserver
  sessionAffinity: None
  type: LoadBalancer

---
#
# kubectl -n spark-apps port-forward svc/spark-apps-jmx-service 8090:8090
#
apiVersion: v1
kind: Service
metadata:
  name: spark-apps-jmx-service
  labels:
    app.kubernetes.io/name: spark-apps-jmx-service
    app.kubernetes.io/component: spark-apps
spec:
  type: NodePort
  ports:
    - name: spark-apps-jmx-service
      port: 8090
      targetPort: 8090
      nodePort: 31809
      protocol: TCP
  selector:
    app.kubernetes.io/metrics-by: jmx
#
---
#
# kubectl -n spark-apps apply svc/spark-apps-prom-service
#
# kubectl -n spark-apps delete svc/spark-apps-prom-service
#
# kubectl -n spark-apps port-forward svc/spark-apps-prom-service 4040:4040
#
---
apiVersion: v1
kind: Service
metadata:
  name: spark-apps-prom-service
  labels:
    app.kubernetes.io/name: spark-apps-prom-service
    app.kubernetes.io/component: spark-apps
spec:
  type: NodePort
  ports:
    - name: spark-apps-prom-service
      nodePort: 31404
      port: 4040
      targetPort: 4040
      protocol: TCP
  selector:
    spark-role: driver
#
---
#
